"""identity_catalog_jobs

Revision ID: 0001
Revises:
Create Date: 2026-10-10 22:48:15.855450
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('region_code', sa.String(length=12), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('parent_entity_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('location_note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name=op.f('ck_entities_latitude_range')),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)', name=op.f('ck_entities_longitude_range')),
    sa.ForeignKeyConstraint(['parent_entity_id'], ['entities.id'], name=op.f('fk_entities_parent_entity_id_entities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities'))
    )
    op.create_index('ix_entities_type_region_status', 'entities', ['type', 'region_code', 'status'], unique=False)
    op.create_table('metrics',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('supported_entity_types', sa.JSON(), nullable=False),
    sa.Column('aggregation_rule', sa.String(length=48), nullable=False),
    sa.Column('comparability_note', sa.Text(), nullable=False),
    sa.Column('dictionary_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_metrics'))
    )
    op.create_table('sources',
    sa.Column('publisher', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('native_grain', sa.String(length=48), nullable=True),
    sa.Column('usage_note', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.String(length=48), nullable=False),
    sa.Column('coverage_start', sa.Date(), nullable=True),
    sa.Column('coverage_end', sa.Date(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('update_frequency', sa.String(length=48), nullable=False),
    sa.Column('adapter_key', sa.String(length=64), nullable=False),
    sa.Column('adapter_config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_index('ix_sources_enabled_last_checked', 'sources', ['enabled', 'last_checked_at'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('jobs',
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_version', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('result_refs', sa.JSON(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_jobs_attempt_count_nonnegative')),
    sa.CheckConstraint('imported_count >= 0', name=op.f('ck_jobs_imported_count_nonnegative')),
    sa.CheckConstraint('processed_count >= 0', name=op.f('ck_jobs_processed_count_nonnegative')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_jobs_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('type', 'idempotency_key', name='type_idempotency')
    )
    op.create_index('ix_jobs_claim', 'jobs', ['status', 'available_at', 'created_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id_hash', name=op.f('pk_sessions'))
    )
    op.create_index('ix_sessions_user_expires', 'sessions', ['user_id', 'expires_at'], unique=False)
    op.create_table('job_attempts',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('lease_token', sa.String(length=36), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(length=48), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('attempt_no > 0', name=op.f('ck_job_attempts_attempt_no_positive')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_attempts_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_attempts')),
    sa.UniqueConstraint('job_id', 'attempt_no', name='job_attempt_no'),
    sa.UniqueConstraint('lease_token', name=op.f('uq_job_attempts_lease_token'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_attempts')
    op.drop_index('ix_sessions_user_expires', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('users')
    op.drop_index('ix_sources_enabled_last_checked', table_name='sources')
    op.drop_table('sources')
    op.drop_table('metrics')
    op.drop_index('ix_entities_type_region_status', table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
