"""ingestion_observations

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-10 22:48:20.290471
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series_policies',
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('metric_code', sa.String(length=48), nullable=False),
    sa.Column('grain', sa.String(length=48), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('valid_until >= valid_from', name=op.f('ck_series_policies_valid_period_order')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_series_policies_entity_id_entities')),
    sa.ForeignKeyConstraint(['metric_code'], ['metrics.code'], name=op.f('fk_series_policies_metric_code_metrics')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_series_policies_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series_policies'))
    )
    op.create_index('ix_series_policies_lookup', 'series_policies', ['entity_id', 'metric_code', 'grain', 'valid_from', 'valid_until'], unique=False)
    op.create_table('source_assets',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('usage_note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('byte_size >= 0', name=op.f('ck_source_assets_byte_size_nonnegative')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_assets_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_assets')),
    sa.UniqueConstraint('source_id', 'sha256', name='source_sha256')
    )
    op.create_table('ingestion_runs',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('parser_version', sa.String(length=64), nullable=False),
    sa.Column('normalizer_version', sa.String(length=64), nullable=False),
    sa.Column('quality_rule_version', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('revised_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('quarantined_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('imported_count >= 0', name=op.f('ck_ingestion_runs_imported_count_nonnegative')),
    sa.CheckConstraint('processed_count >= 0', name=op.f('ck_ingestion_runs_processed_count_nonnegative')),
    sa.CheckConstraint('quarantined_count >= 0', name=op.f('ck_ingestion_runs_quarantined_count_nonnegative')),
    sa.CheckConstraint('revised_count >= 0', name=op.f('ck_ingestion_runs_revised_count_nonnegative')),
    sa.CheckConstraint('skipped_count >= 0', name=op.f('ck_ingestion_runs_skipped_count_nonnegative')),
    sa.ForeignKeyConstraint(['asset_id'], ['source_assets.id'], name=op.f('fk_ingestion_runs_asset_id_source_assets')),
    sa.ForeignKeyConstraint(['attempt_id'], ['job_attempts.id'], name=op.f('fk_ingestion_runs_attempt_id_job_attempts')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_ingestion_runs_job_id_jobs')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_ingestion_runs_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    op.create_index('ix_ingestion_runs_source_started', 'ingestion_runs', ['source_id', 'started_at'], unique=False)
    op.create_table('observations',
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('metric_code', sa.String(length=48), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('grain', sa.String(length=48), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('original_value', sa.String(length=100), nullable=False),
    sa.Column('original_unit', sa.String(length=24), nullable=False),
    sa.Column('conversion_factor', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=False),
    sa.Column('source_locator', sa.String(length=500), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('quality_status', sa.String(length=48), nullable=False),
    sa.Column('methodology_version', sa.String(length=64), nullable=False),
    sa.Column('value_kind', sa.String(length=48), nullable=False),
    sa.Column('derivation_manifest', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name=op.f('ck_observations_period_order')),
    sa.CheckConstraint('value >= 0', name=op.f('ck_observations_value_nonnegative')),
    sa.ForeignKeyConstraint(['asset_id'], ['source_assets.id'], name=op.f('fk_observations_asset_id_source_assets')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_observations_entity_id_entities')),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], name=op.f('fk_observations_ingestion_run_id_ingestion_runs')),
    sa.ForeignKeyConstraint(['metric_code'], ['metrics.code'], name=op.f('fk_observations_metric_code_metrics')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_observations_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations')),
    sa.UniqueConstraint('entity_id', 'metric_code', 'period_start', 'period_end', 'grain', 'source_id', name='observation_business_key')
    )
    op.create_index('ix_observations_series', 'observations', ['entity_id', 'metric_code', 'grain', 'period_start'], unique=False)
    op.create_table('observation_revisions',
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('superseded_by_run_id', sa.String(length=36), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_observation_revisions_observation_id_observations')),
    sa.ForeignKeyConstraint(['superseded_by_run_id'], ['ingestion_runs.id'], name=op.f('fk_observation_revisions_superseded_by_run_id_ingestion_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observation_revisions')),
    sa.UniqueConstraint('observation_id', 'version', name='observation_version')
    )
    op.create_table('quality_issues',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=True),
    sa.Column('row_locator', sa.String(length=300), nullable=True),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=48), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_quality_issues_observation_id_observations')),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], name=op.f('fk_quality_issues_run_id_ingestion_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_issues'))
    )
    op.create_index('ix_quality_issues_run_status', 'quality_issues', ['run_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quality_issues_run_status', table_name='quality_issues')
    op.drop_table('quality_issues')
    op.drop_table('observation_revisions')
    op.drop_index('ix_observations_series', table_name='observations')
    op.drop_table('observations')
    op.drop_index('ix_ingestion_runs_source_started', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_table('source_assets')
    op.drop_index('ix_series_policies_lookup', table_name='series_policies')
    op.drop_table('series_policies')
    # ### end Alembic commands ###
