"""topics_knowledge

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-10 22:48:23.865700
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('authority', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=48), nullable=False),
    sa.Column('region_code', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('operator_note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('ends_at IS NULL OR ends_at >= starts_at', name=op.f('ck_events_time_order')),
    sa.ForeignKeyConstraint(['asset_id'], ['source_assets.id'], name=op.f('fk_events_asset_id_source_assets')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_events_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('ix_events_region_status_starts', 'events', ['region_code', 'status', 'starts_at'], unique=False)
    op.create_table('holidays',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days_count', sa.SmallInteger(), nullable=False),
    sa.Column('region_code', sa.String(length=12), nullable=False),
    sa.Column('scope_key', sa.String(length=200), nullable=False),
    sa.Column('definition_source_id', sa.String(length=36), nullable=False),
    sa.Column('definition_asset_id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('days_count > 0', name=op.f('ck_holidays_days_positive')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_holidays_date_order')),
    sa.ForeignKeyConstraint(['definition_asset_id'], ['source_assets.id'], name=op.f('fk_holidays_definition_asset_id_source_assets')),
    sa.ForeignKeyConstraint(['definition_source_id'], ['sources.id'], name=op.f('fk_holidays_definition_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holidays')),
    sa.UniqueConstraint('kind', 'year', 'region_code', 'scope_key', name='holiday_scope')
    )
    op.create_table('knowledge_documents',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('permission_note', sa.Text(), nullable=False),
    sa.Column('document_version', sa.String(length=64), nullable=False),
    sa.Column('index_status', sa.String(length=48), nullable=False),
    sa.Column('active_index_version', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['source_assets.id'], name=op.f('fk_knowledge_documents_asset_id_source_assets')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_knowledge_documents_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents'))
    )
    op.create_table('document_entities',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('fk_document_entities_document_id_knowledge_documents')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_document_entities_entity_id_entities')),
    sa.PrimaryKeyConstraint('document_id', 'entity_id', name=op.f('pk_document_entities'))
    )
    op.create_table('event_entities',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_event_entities_entity_id_entities')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_entities_event_id_events')),
    sa.PrimaryKeyConstraint('event_id', 'entity_id', name=op.f('pk_event_entities'))
    )
    op.create_index('ix_event_entities_entity_event', 'event_entities', ['entity_id', 'event_id'], unique=False)
    op.create_table('event_history',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=False),
    sa.Column('operator_user_id', sa.String(length=36), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_history_event_id_events')),
    sa.ForeignKeyConstraint(['operator_user_id'], ['users.id'], name=op.f('fk_event_history_operator_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_history')),
    sa.UniqueConstraint('event_id', 'version', name='event_version')
    )
    op.create_table('knowledge_indexes',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('parser_version', sa.String(length=64), nullable=False),
    sa.Column('embedding_model_version', sa.String(length=100), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('chunk_count >= 0', name=op.f('ck_knowledge_indexes_chunk_count_nonnegative')),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('fk_knowledge_indexes_document_id_knowledge_documents')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_knowledge_indexes_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_indexes')),
    sa.UniqueConstraint('document_id', 'version', name='document_index_version')
    )
    op.create_table('knowledge_chunks',
    sa.Column('index_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_no', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('locator', sa.JSON(), nullable=False),
    sa.Column('text_sha256', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('chunk_no >= 0', name=op.f('ck_knowledge_chunks_chunk_no_nonnegative')),
    sa.ForeignKeyConstraint(['index_id'], ['knowledge_indexes.id'], name=op.f('fk_knowledge_chunks_index_id_knowledge_indexes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunks')),
    sa.UniqueConstraint('index_id', 'chunk_no', name='index_chunk_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_chunks')
    op.drop_table('knowledge_indexes')
    op.drop_table('event_history')
    op.drop_index('ix_event_entities_entity_event', table_name='event_entities')
    op.drop_table('event_entities')
    op.drop_table('document_entities')
    op.drop_table('knowledge_documents')
    op.drop_table('holidays')
    op.drop_index('ix_events_region_status_starts', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
