"""video_forecasts

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-10 22:48:27.842553
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_runs',
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('metric_code', sa.String(length=48), nullable=False),
    sa.Column('grain', sa.String(length=48), nullable=False),
    sa.Column('training_start', sa.Date(), nullable=False),
    sa.Column('training_end', sa.Date(), nullable=False),
    sa.Column('horizon', sa.SmallInteger(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('model_config', sa.JSON(), nullable=False),
    sa.Column('input_manifest', sa.JSON(), nullable=False),
    sa.Column('input_sha256', sa.String(length=64), nullable=False),
    sa.Column('backtest', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('horizon > 0', name=op.f('ck_forecast_runs_horizon_positive')),
    sa.CheckConstraint('training_end >= training_start', name=op.f('ck_forecast_runs_training_period_order')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_forecast_runs_entity_id_entities')),
    sa.ForeignKeyConstraint(['metric_code'], ['metrics.code'], name=op.f('fk_forecast_runs_metric_code_metrics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_runs'))
    )
    op.create_table('permission_records',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('grantor', sa.String(length=200), nullable=False),
    sa.Column('evidence_path', sa.String(length=500), nullable=False),
    sa.Column('evidence_sha256', sa.String(length=64), nullable=False),
    sa.Column('allowed_uses', sa.JSON(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('playback_allowed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_permission_records_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission_records'))
    )
    op.create_table('forecast_points',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('lower_bound', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('upper_bound', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('lower_bound <= value AND value <= upper_bound', name=op.f('ck_forecast_points_forecast_bounds')),
    sa.CheckConstraint('lower_bound >= 0', name=op.f('ck_forecast_points_forecast_nonnegative')),
    sa.CheckConstraint('period_end >= period_start', name=op.f('ck_forecast_points_forecast_period_order')),
    sa.ForeignKeyConstraint(['run_id'], ['forecast_runs.id'], name=op.f('fk_forecast_points_run_id_forecast_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_points')),
    sa.UniqueConstraint('run_id', 'period_start', 'period_end', name='forecast_period')
    )
    op.create_table('videos',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('scenic_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('permission_record_id', sa.String(length=36), nullable=False),
    sa.Column('recorded_start_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_end_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('camera_location_note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('recorded_end_at > recorded_start_at', name=op.f('ck_videos_recorded_time_order')),
    sa.ForeignKeyConstraint(['asset_id'], ['source_assets.id'], name=op.f('fk_videos_asset_id_source_assets')),
    sa.ForeignKeyConstraint(['camera_id'], ['entities.id'], name=op.f('fk_videos_camera_id_entities')),
    sa.ForeignKeyConstraint(['permission_record_id'], ['permission_records.id'], name=op.f('fk_videos_permission_record_id_permission_records')),
    sa.ForeignKeyConstraint(['scenic_id'], ['entities.id'], name=op.f('fk_videos_scenic_id_entities')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_videos_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos'))
    )
    op.create_index('ix_videos_location_time', 'videos', ['scenic_id', 'camera_id', 'recorded_start_at'], unique=False)
    op.create_table('manual_annotations',
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('sample_key', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('entries', sa.Integer(), nullable=False),
    sa.Column('exits', sa.Integer(), nullable=False),
    sa.Column('annotator', sa.String(length=100), nullable=False),
    sa.Column('direction_note', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=48), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('entries >= 0', name=op.f('ck_manual_annotations_annotation_entries_nonnegative')),
    sa.CheckConstraint('exits >= 0', name=op.f('ck_manual_annotations_annotation_exits_nonnegative')),
    sa.CheckConstraint('window_end > window_start', name=op.f('ck_manual_annotations_annotation_window_order')),
    sa.ForeignKeyConstraint(['camera_id'], ['entities.id'], name=op.f('fk_manual_annotations_camera_id_entities')),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_manual_annotations_video_id_videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_annotations')),
    sa.UniqueConstraint('video_id', 'sample_key', 'version', name='video_sample_version')
    )
    op.create_table('video_analyses',
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('detector_model_version', sa.String(length=100), nullable=False),
    sa.Column('detector_sha256', sa.String(length=64), nullable=False),
    sa.Column('openvino_version', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=48), nullable=False),
    sa.Column('tracker_config_id', sa.String(length=100), nullable=True),
    sa.Column('tracker_config', sa.JSON(), nullable=False),
    sa.Column('count_line', sa.JSON(), nullable=False),
    sa.Column('entry_side', sa.String(length=48), nullable=False),
    sa.Column('interval_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('config_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('manual_validation', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('interval_minutes IN (1, 5, 15)', name=op.f('ck_video_analyses_interval_allowed')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_video_analyses_job_id_jobs')),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_analyses_video_id_videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_analyses')),
    sa.UniqueConstraint('job_id', name=op.f('uq_video_analyses_job_id')),
    sa.UniqueConstraint('video_id', 'config_sha256', name='video_analysis_config')
    )
    op.create_table('camera_counts',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('entries', sa.Integer(), nullable=False),
    sa.Column('exits', sa.Integer(), nullable=False),
    sa.Column('quality_status', sa.String(length=48), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('entries >= 0', name=op.f('ck_camera_counts_entries_nonnegative')),
    sa.CheckConstraint('exits >= 0', name=op.f('ck_camera_counts_exits_nonnegative')),
    sa.CheckConstraint('window_end > window_start', name=op.f('ck_camera_counts_window_order')),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], name=op.f('fk_camera_counts_analysis_id_video_analyses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camera_counts')),
    sa.UniqueConstraint('analysis_id', 'window_start', 'window_end', name='analysis_window')
    )
    op.create_index('ix_camera_counts_analysis_start', 'camera_counts', ['analysis_id', 'window_start'], unique=False)
    op.create_table('short_forecast_runs',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('cutoff_at', sa.DateTime(), nullable=False),
    sa.Column('direction', sa.String(length=48), nullable=False),
    sa.Column('horizon_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('step_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('model_config', sa.JSON(), nullable=False),
    sa.Column('input_manifest', sa.JSON(), nullable=False),
    sa.Column('input_sha256', sa.String(length=64), nullable=False),
    sa.Column('validation_error', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('horizon_minutes IN (15, 30, 60)', name=op.f('ck_short_forecast_runs_short_horizon_allowed')),
    sa.CheckConstraint('step_minutes IN (5, 15)', name=op.f('ck_short_forecast_runs_short_step_allowed')),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], name=op.f('fk_short_forecast_runs_analysis_id_video_analyses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_short_forecast_runs'))
    )
    op.create_table('short_forecast_points',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('lower_bound', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('upper_bound', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(lower_bound IS NULL AND upper_bound IS NULL) OR (lower_bound IS NOT NULL AND upper_bound IS NOT NULL AND lower_bound <= value AND value <= upper_bound)', name=op.f('ck_short_forecast_points_short_bounds')),
    sa.CheckConstraint('value >= 0', name=op.f('ck_short_forecast_points_short_value_nonnegative')),
    sa.CheckConstraint('window_end > window_start', name=op.f('ck_short_forecast_points_short_window_order')),
    sa.ForeignKeyConstraint(['run_id'], ['short_forecast_runs.id'], name=op.f('fk_short_forecast_points_run_id_short_forecast_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_short_forecast_points')),
    sa.UniqueConstraint('run_id', 'window_start', 'window_end', name='short_forecast_window')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_forecast_points')
    op.drop_table('short_forecast_runs')
    op.drop_index('ix_camera_counts_analysis_start', table_name='camera_counts')
    op.drop_table('camera_counts')
    op.drop_table('video_analyses')
    op.drop_table('manual_annotations')
    op.drop_index('ix_videos_location_time', table_name='videos')
    op.drop_table('videos')
    op.drop_table('forecast_points')
    op.drop_table('permission_records')
    op.drop_table('forecast_runs')
    # ### end Alembic commands ###
